### ISSUE TITLE
boostrap.sh faild

### ISSUE THREAD

**Issue by CodingJzy** [dfinity/cancan#16] opened 2021-05-14 02:12 UTC
![image](https://user-images.githubusercontent.com/44855157/118210303-ee3ff980-b49c-11eb-9d5a-aac4602359ad.png)

**Comment by kritzcreek** [comment] 2021-05-14 07:06
Did you accidentally change this line around? https://github.com/dfinity/cancan/blob/4c70e19c7d82c8995e60e9d57f1cafeef068c3a1/package-set.dhall#L10

It says 0.7.0 in there, but it looks like you're trying to clone a tag with 0.6.0, which doesn't exist.

**Comment by gobengo** [comment] 2021-05-21 19:16
I haven't been able to reproduce this while devving this week. We also just landed a new commit in the main branch that slightly changes the local dev setup. I just dig a fresh clone, followed the readme, and didn't see any error like this while `./bootstrap.sh` succeeded.

Since it's been a week, I'm going to close this, but please reopen or refile with more details if this continues to happen on a fresh checkout, and we'll take another look.

**Closed by gobengo** 2021-05-21 19:16 UTC
